{% set name = "tad-mctc" %}
{% set version = "0.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/tad_mctc-{{ version }}.tar.gz
  sha256: 2945fd517c4204f9dfaa9d357da1014dcab02a5626d5f9c835390fb37d459d3a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - opt-einsum
    - packaging  # otherwise, `pip check` fails for qcelemental
    - pytorch >=2.6,<3
    - typing-extensions

test:
  imports:
    - tad_mctc
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/tad-mctc/tad-mctc
  summary: Torch Autodiff Utility
  dev_url: https://github.com/tad-mctc/tad-mctc
  doc_url: https://tad-mctc.readthedocs.io/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marvinfriede
