{% set name = "tad-mctc" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tad_mctc-{{ version }}.tar.gz
  sha256: 4f46ba9b3976d2cd77092c68e9730fc256840a4a8e5e137384051658774687e0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - numpy
    - opt-einsum
    - psutil
    - scipy
    - pytorch >=1.11
    - typing-extensions

test:
  imports:
    - tad_mctc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tad-mctc/tad-mctc
  summary: Torch Autodiff Utility
  dev_url: https://github.com/tad-mctc/tad-mctc
  doc_url: https://tad-mctc.readthedocs.io/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marvinfriede
