{% set name = "tad-mctc" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/tad_mctc-{{ version }}.tar.gz
  sha256: 38ffc59669badf92ada66bf79766f35ecde9fc856d200eaeb4498f9d8ec0d234

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.13
    - setuptools
    - pip
  run:
    - python >=3.8,<3.13
    - numpy <2
    - opt-einsum
    - psutil
    - scipy
    - pytorch >=1.11,<3
    - typing-extensions

test:
  imports:
    - tad_mctc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tad-mctc/tad-mctc
  summary: Torch Autodiff Utility
  dev_url: https://github.com/tad-mctc/tad-mctc
  doc_url: https://tad-mctc.readthedocs.io/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marvinfriede
