{% set name = "tad-mctc" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tad_mctc-{{ version }}.tar.gz
  sha256: 31088d4388bdb83c34fdab391e7e56250f528631bd82645509e913c997e82736

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.13
    - setuptools
    - pip
  run:
    - python >=3.8,<3.13
    - numpy <2
    - opt-einsum
    - psutil
    - scipy
    - pytorch >=1.11,<2.5
    - typing-extensions

test:
  imports:
    - tad_mctc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tad-mctc/tad-mctc
  summary: Torch Autodiff Utility
  dev_url: https://github.com/tad-mctc/tad-mctc
  doc_url: https://tad-mctc.readthedocs.io/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marvinfriede
